name: CI

on: [push]

jobs:
  build:

    runs-on: macOS-10.14
    
    steps:
    - uses: actions/checkout@v1
    - name: pod install 
      run: | 
        gem install cocoapods
        cd Example
        pod install
